import os
import requests
from bs4 import BeautifulSoup
from langdetect import detect
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pickle

# Set the search queries
search_queries = [
    "Ayurveda Herbs",
    "Ayurveda Medicines",
    "Ayurveda Diseases",
    "Ayurveda Treatments",
    "Ayurveda Therapy",
    "Ayurveda Nutrition",
    "Ayurveda Diet",
    "Ayurveda Lifestyle",
    "Ayurveda Practices",
    "Ayurveda Yoga",
    "Ayurveda Massage",
    "Ayurveda Remedies",
    "Ayurveda Detox",
    "Ayurveda Panchakarma",
    "Ayurveda Doshas",
    "Ayurveda Vata",
    "Ayurveda Pitta",
    "Ayurveda Kapha",
    "Ayurveda Body Types",
    "Ayurveda Holistic Health",
    "Ayurveda Wellness",
    "Ayurveda Skin Care",
    "Ayurveda Hair Care",
    "Ayurveda Oils",
    "Ayurveda Spices",
    "Ayurveda Immunity",
    "Ayurveda Stress Relief",
    "Ayurveda Meditation",
    "Ayurveda Natural Healing",
    "Ayurveda Cleansing",
    "Ayurveda Weight Loss",
    "Ayurveda Anti-aging",
    "Ayurveda Pain Relief",
    "Ayurveda Sleep Disorders",
    "Ayurveda Mental Health",
    "Ayurveda Chronic Illness",
    "Ayurveda Diabetes",
    "Ayurveda Hypertension",
    "Ayurveda Heart Health",
    "Ayurveda Respiratory Health",
    "Ayurveda Digestive Health",
    "Ayurveda Joint Health",
    "Ayurveda Bone Health",
    "Ayurveda Eye Health",
    "Ayurveda Ear Health",
    "Ayurveda Oral Health",
    "Ayurveda Women's Health",
    "Ayurveda Men's Health",
    "Ayurveda Children's Health",
    "Ayurveda Seasonal Regimen",
    "Ayurveda Daily Routine",
    "Ayurveda Beauty Tips",
    "Ayurveda Hair Growth",
    "Ayurveda Weight Gain",
    "Ayurveda Healthy Recipes",
    "Ayurveda Cooking",
    "Ayurveda Herbal Teas",
    "Ayurveda Drinks",
    "Ayurveda Supplements",
    "Ayurveda Organic Products",
    "Ayurveda Essential Oils",
    "Ayurveda Plants",
    "Ayurveda Seeds",
    "Ayurveda Fruits",
    "Ayurveda Vegetables",
    "Ayurveda Roots",
    "Ayurveda Leaves",
    "Ayurveda Flowers",
    "Ayurveda Shrubs",
    "Ayurveda Trees",
    "Ayurveda Healing Properties",
    "Ayurveda Traditional Medicine",
    "Ayurveda History",
    "Ayurveda Philosophy",
    "Ayurveda Spirituality",
    "Ayurveda Mind-Body Connection",
    "Ayurveda Research",
    "Ayurveda Education",
    "Ayurveda Courses",
    "Ayurveda Certification",
    "Ayurveda Practitioners",
    "Ayurveda Clinics",
    "Ayurveda Hospitals",
    "Ayurveda Tourism",
    "Ayurveda in India",
    "Ayurveda Worldwide",
    "Ayurveda Modern Applications",
    "Ayurveda and Science",
    "Ayurveda Myths",
    "Ayurveda Benefits",
    "Ayurveda for Pets",
    "Ayurveda Environmental Impact",
    "Ayurveda Organic Farming",
    "Ayurveda Farming Practices",
    "Ayurveda Community",
    "Ayurveda Workshops",
    "Ayurveda Events",
    "Ayurveda Blogs",
    "Ayurveda Books",
    "Ayurveda Cosmetics",
    "Ayurveda Bath Products",
    "Ayurveda Baby Care",
    "Ayurveda Pet Care",
    "Ayurveda Animal Health",
    "Ayurveda Home Remedies",
    "Ayurveda Detox Diets",
    "Ayurveda Cold Remedies",
    "Ayurveda Fever Remedies",
    "Ayurveda Headache Remedies",
    "Ayurveda Allergy Remedies",
    "Ayurveda Cancer Support",
    "Ayurveda Immune Boosting",
    "Ayurveda Bone Density",
    "Ayurveda Athletic Performance",
    "Ayurveda Adaptogens",
    "Ayurveda Anti-inflammatory",
    "Ayurveda Cholesterol Management",
    "Ayurveda Blood Pressure",
    "Ayurveda Gut Health",
    "Ayurveda Probiotics",
    "Ayurveda Adaptogen Herbs",
    "Ayurveda Functional Foods",
    "Ayurveda Hormone Balance",
    "Ayurveda Detox Drinks",
    "Ayurveda Smoothies",
    "Ayurveda Soups",
    "Ayurveda Sauces",
    "Ayurveda Spreads",
    "Ayurveda Condiments",
    "Ayurveda Beauty Products",
    "Ayurveda Personal Care",
    "Ayurveda Oral Hygiene",
    "Ayurveda Dental Care",
    "Ayurveda Aroma Therapy",
    "Ayurveda Self-care",
    "Ayurveda Mental Wellness",
    "Ayurveda Journals",
    "Ayurveda Supplements Reviews",
    "Ayurveda Tea Reviews",
    "Ayurveda Essential Oils Reviews",
    "Ayurveda Spa Treatments",
    "Ayurveda Facial Treatments",
    "Ayurveda Eye Treatments",
    "Ayurveda Hearing Treatments",
    "Ayurveda Sleep Therapy",
    "Ayurveda Sleep Hygiene",
    "Ayurveda Fitness",
    "Ayurveda Exercise",
    "Ayurveda Sports Nutrition",
    "Ayurveda Energy Boosters",
    "Ayurveda Superfoods",
    "Ayurveda Hydration",
    "Ayurveda Bone Broth",
    "Ayurveda Herbal Infusions",
    "Ayurveda Balms",
    "Ayurveda Salves",
    "Ayurveda Lotions",
    "Ayurveda Creams",
    "Ayurveda Moisturizers",
    "Ayurveda Face Masks",
    "Ayurveda Hair Masks",
    "Ayurveda Shampoos",
    "Ayurveda Conditioners",
    "Ayurveda Serums",
    "Ayurveda Toners",
    "Ayurveda Cleansers",
    "Ayurveda Facial Oils",
    "Ayurveda Body Oils",
    "Ayurveda Scrubs",
    "Ayurveda Bath Salts",
    "Ayurveda Exfoliators",
    "Ayurveda Foot Care",
    "Ayurveda Hand Care",
    "Ayurveda Nail Care",
    "Ayurveda Lip Care",
    "Ayurveda Anti-Aging Skin Care",
    "Ayurveda Sun Protection",
    "Ayurveda After-Sun Care",
    "Ayurveda Eye Creams",
    "Ayurveda Lip Balms",
    "Ayurveda Beard Oils",
    "Ayurveda Beard Balms",
    "Ayurveda Hair Styling",
    "Ayurveda Hair Treatments",
    "Ayurveda Hair Serums",
    "Ayurveda Hair Oils",
    "Ayurveda Scalp Treatments",
    "Ayurveda Hair Loss Treatments",
    "Ayurveda Hair Growth Serums",
    "Ayurveda Heat Protectants",
    "Ayurveda Hair Dyes",
    "Ayurveda Hair Care Routines",
    "Ayurveda Hair Accessories",
    "Ayurveda Hair Tools",
    "Ayurveda Bath Accessories",
    "Ayurveda Body Brushes",
    "Ayurveda Foot Massagers",
    "Ayurveda Eye Massagers",
    "Ayurveda Face Rollers",
    "Ayurveda Gua Sha",
    "Ayurveda Scalp Massagers",
    "Ayurveda Face Tools",
    "Ayurveda Fitness Equipment",
    "Ayurveda Yoga Mats",
    "Ayurveda Meditation Cushions",
    "Ayurveda Incense",
    "Ayurveda Candles",
    "Ayurveda Crystals",
    "Ayurveda Jewelry",
    "Ayurveda Home Decor",
    "Ayurveda Bedding",
    "Ayurveda Pillows",
    "Ayurveda Throws",
    "Ayurveda Rugs",
    "Ayurveda Wall Art",
    "Ayurveda Kitchenware",
    "Ayurveda Tableware",
    "Ayurveda Cookware",
    "Ayurveda Storage Solutions",
    "Ayurveda Cleaning Products",
    "Ayurveda Natural Cleaners",
    "Ayurveda Sustainable Living",
    "Ayurveda Green Living",
    "Ayurveda Eco-Friendly Products",
    "Ayurveda Zero Waste",
    "Ayurveda Minimalism",
    "Ayurveda Decluttering",
    "Ayurveda Feng Shui",
    "Ayurveda Space Clearing",
    "Ayurveda Plant Care",
    "Ayurveda Gardening",
    "Ayurveda Indoor Plants",
    "Ayurveda Outdoor Plants",
    "Ayurveda Herbal Gardens",
    "Ayurveda Organic Gardening",
    "Ayurveda Garden Design",
    "Ayurveda Companion Planting",
    "Ayurveda Permaculture",
    "Ayurveda Beekeeping",
    "Ayurveda Aquaponics",
    "Ayurveda Hydroponics",
    "Ayurveda Farm-to-Table",
    "Ayurveda Seasonal Eating",
    "Ayurveda Local Food",
    "Ayurveda Farmers Markets",
    "Ayurveda Community Supported Agriculture",
    "Ayurveda Ethical Eating",
    "Ayurveda Food Justice",
    "Ayurveda Food Security",
    "Ayurveda Urban Gardening",
    "Ayurveda Wildcrafting",
    "Ayurveda Foraging",
    "Ayurveda Herbalism",
    "Ayurveda Plant Medicine",
    "Ayurveda Traditional Healing",
    "Ayurveda Indigenous Wisdom",
    "Ayurveda Ancestral Knowledge",
    "Ayurveda Cultural Heritage",
    "Ayurveda Sacred Plants",
    "Ayurveda Rituals",
    "Ayurveda Ceremonies",
    "Ayurveda Festivities",
    "Ayurveda Holidays",
    "Ayurveda Traditions",
    "Ayurveda Legends",
    "Ayurveda Folklore",
    "Ayurveda Mythology",
    "Ayurveda Stories",
    "Ayurveda Wisdom",
    "Ayurveda Teachings",
    "Ayurveda Elders",
    "Ayurveda Lineages",
    "Ayurveda Mentorship",
    "Ayurveda Apprenticeship",
    "Ayurveda Internships",
    "Ayurveda Career Opportunities",
    "Ayurveda Job Listings",
    "Ayurveda Employment",
    "Ayurveda Volunteering",
    "Ayurveda Internships Abroad",
    "Ayurveda Study Abroad",
    "Ayurveda Exchange Programs",
    "Ayurveda Scholarships",
    "Ayurveda Grants",
    "Ayurveda Fellowships",
    "Ayurveda Conferences",
    "Ayurveda Webinars",
    "Ayurveda Online Courses",
    "Ayurveda Distance Learning",
    "Ayurveda E-Learning",
    "Ayurveda Virtual Classes",
    "Ayurveda Digital Resources",
    "Ayurveda Podcasts",
    "Ayurveda Vlogs",
    "Ayurveda YouTube Channels",
    "Ayurveda Instagram Accounts",
    "Ayurveda Facebook Groups",
    "Ayurveda Twitter Accounts",
    "Ayurveda Pinterest Boards",
    "Ayurveda LinkedIn Groups",
    "Ayurveda Networking",
    "Ayurveda Forums",
    "Ayurveda Online Communities",
    "Ayurveda Social Media",
    "Ayurveda Influencers",
    "Ayurveda Brand Ambassadors",
    "Ayurveda Product Reviews",
    "Ayurveda Testimonials",
    "Ayurveda Case Studies",
    "Ayurveda Clinical Trials",
    "Ayurveda Research Papers",
    "Ayurveda Scientific Studies",
    "Ayurveda Journals",
    "Ayurveda Magazines",
    "Ayurveda Newsletters",
    "Ayurveda Press Releases",
    "Ayurveda Media Coverage",
    "Ayurveda News",
    "Ayurveda Trends",
    "Ayurveda Innovations",
    "Ayurveda New Products",
    "Ayurveda Product Launches",
    "Ayurveda Market Analysis",
    "Ayurveda Industry Insights",
    "Ayurveda Business Opportunities",
    "Ayurveda Entrepreneurship",
    "Ayurveda Startups",
    "Ayurveda Investment",
    "Ayurveda Funding",
    "Ayurveda Crowdfunding",
    "Ayurveda Partnerships",
    "Ayurveda Collaborations",
    "Ayurveda Alliances",
    "Ayurveda Joint Ventures",
    "Ayurveda Licensing",
    "Ayurveda Franchising",
    "Ayurveda Retail",
    "Ayurveda E-commerce",
    "Ayurveda Wholesale",
    "Ayurveda Distribution",
    "Ayurveda Supply Chain",
    "Ayurveda Logistics",
    "Ayurveda Export",
    "Ayurveda Import",
    "Ayurveda Trade Shows",
    "Ayurveda Expos",
    "Ayurveda Fairs",
    "Ayurveda Markets",
    "Ayurveda Stores",
    "Ayurveda Boutiques",
    "Ayurveda Pop-Up Shops",
    "Ayurveda Farmers Markets",
    "Ayurveda Craft Fairs",
    "Ayurveda Artisanal Products",
    "Ayurveda Handcrafted Products",
    "Ayurveda Small Businesses",
    "Ayurveda Artisans",
    "Ayurveda Makers",
    "Ayurveda Creators",
    "Ayurveda Designers",
    "Ayurveda Artists",
    "Ayurveda Innovators",
    "Ayurveda Entrepreneurs",
    "Ayurveda Influencers",
    "Ayurveda Thought Leaders",
    "Ayurveda Visionaries",
    "Ayurveda Pioneers",
    "Ayurveda Trailblazers",
    "Ayurveda Changemakers",
    "Ayurveda Advocates",
    "Ayurveda Activists",
    "Ayurveda Leaders",
    "Ayurveda Community Leaders",
    "Ayurveda Nonprofits",
    "Ayurveda NGOs",
    "Ayurveda Philanthropy",
    "Ayurveda Volunteering",
    "Ayurveda Community Service",
    "Ayurveda Social Impact",
    "Ayurveda Social Responsibility",
    "Ayurveda Corporate Social Responsibility",
    "Ayurveda Ethical Practices",
    "Ayurveda Sustainable Practices",
    "Ayurveda Environmental Stewardship",
    "Ayurveda Conservation",
    "Ayurveda Wildlife Protection",
    "Ayurveda Habitat Restoration",
    "Ayurveda Climate Action",
    "Ayurveda Renewable Energy",
    "Ayurveda Green Energy",
    "Ayurveda Energy Efficiency",
    "Ayurveda Carbon Footprint",
    "Ayurveda Carbon Neutrality",
    "Ayurveda Offsetting",
    "Ayurveda Sustainable Design",
    "Ayurveda Eco-Architecture",
    "Ayurveda Green Building",
    "Ayurveda LEED Certification",
    "Ayurveda Healthy Homes",
    "Ayurveda Wellness Architecture",
    "Ayurveda Biophilic Design",
    "Ayurveda Natural Materials",
    "Ayurveda Organic Materials",
    "Ayurveda Non-Toxic Materials",
    "Ayurveda Recycled Materials",
    "Ayurveda Upcycling",
    "Ayurveda Repurposing",
    "Ayurveda Waste Reduction",
    "Ayurveda Waste Management",
    "Ayurveda Composting",
    "Ayurveda Recycling",
    "Ayurveda Circular Economy",
    "Ayurveda Sustainable Economy",
    "Ayurveda Local Economy",
    "Ayurveda Community Economy",
    "Ayurveda Cooperative Economy",
    "Ayurveda Shared Economy",
    "Ayurveda Social Enterprises",
    "Ayurveda B Corps",
    "Ayurveda Fair Trade",
    "Ayurveda Ethical Trade",
    "Ayurveda Transparent Trade",
    "Ayurveda Fair Wages",
    "Ayurveda Worker Rights",
    "Ayurveda Labor Practices",
    "Ayurveda Human Rights",
    "Ayurveda Gender Equality",
    "Ayurveda Racial Equality",
    "Ayurveda Social Justice",
    "Ayurveda Economic Justice",
    "Ayurveda Environmental Justice",
    "Ayurveda Health Equity",
    "Ayurveda Global Health",
    "Ayurveda Public Health",
    "Ayurveda Health Policy",
    "Ayurveda Health Systems",
    "Ayurveda Healthcare Access",
    "Ayurveda Healthcare Delivery",
    "Ayurveda Health Programs",
    "Ayurveda Health Initiatives",
    "Ayurveda Health Campaigns",
    "Ayurveda Health Education",
    "Ayurveda Health Promotion",
    "Ayurveda Disease Prevention",
    "Ayurveda Health Screening",
    "Ayurveda Health Surveillance",
    "Ayurveda Health Data",
    "Ayurveda Health Informatics",
    "Ayurveda Health Technology",
    "Ayurveda Telemedicine",
    "Ayurveda Digital Health",
    "Ayurveda Health Apps",
    "Ayurveda Health Wearables",
    "Ayurveda Health Trackers",
    "Ayurveda Health Analytics",
    "Ayurveda Health Research",
    "Ayurveda Health Studies",
    "Ayurveda Health Publications",
    "Ayurveda Health Conferences",
    "Ayurveda Health Workshops",
    "Ayurveda Health Seminars",
    "Ayurveda Health Training",
    "Ayurveda Health Careers",
    "Ayurveda Health Professions",
    "Ayurveda Health Certifications",
    "Ayurveda Health Licenses",
    "Ayurveda Health Regulations",
    "Ayurveda Health Standards",
    "Ayurveda Health Guidelines",
    "Ayurveda Health Policies",
    "Ayurveda Health Laws",
    "Ayurveda Health Ethics",
    "Ayurveda Health Governance",
    "Ayurveda Health Advocacy",
    "Ayurveda Patient Advocacy",
    "Ayurveda Patient Rights",
    "Ayurveda Patient Safety",
    "Ayurveda Patient Experience",
    "Ayurveda Patient Engagement",
    "Ayurveda Patient Education",
    "Ayurveda Patient Support",
    "Ayurveda Patient Empowerment",
    "Ayurveda Patient-Centered Care",
    "Ayurveda Family-Centered Care",
    "Ayurveda Community-Centered Care",
    "Ayurveda Integrative Care",
    "Ayurveda Coordinated Care",
    "Ayurveda Collaborative Care",
    "Ayurveda Multidisciplinary Care",
    "Ayurveda Holistic Care",
    "Ayurveda Compassionate Care",
    "Ayurveda Palliative Care",
    "Ayurveda Hospice Care",
    "Ayurveda End-of-Life Care",
    "Ayurveda Bereavement Support",
    "Ayurveda Grief Support",
    "Ayurveda Mental Health Support",
    "Ayurveda Peer Support",
    "Ayurveda Support Groups",
    "Ayurveda Counseling",
    "Ayurveda Therapy Services",
    "Ayurveda Coaching",
    "Ayurveda Mentorship Programs",
    "Ayurveda Peer Mentorship",
    "Ayurveda Volunteer Mentorship",
    "Ayurveda Career Mentorship",
    "Ayurveda Business Mentorship",
    "Ayurveda Leadership Mentorship",
    "Ayurveda Academic Mentorship",
    "Ayurveda Student Mentorship",
    "Ayurveda Youth Mentorship",
    "Ayurveda Adult Mentorship",
    "Ayurveda Senior Mentorship",
    "Ayurveda Parent Mentorship",
    "Ayurveda Teacher Mentorship",
    "Ayurveda Faculty Mentorship",
    "Ayurveda Peer Coaching",
    "Ayurveda Life Coaching",
    "Ayurveda Wellness Coaching",
    "Ayurveda Health Coaching",
    "Ayurveda Executive Coaching",
    "Ayurveda Career Coaching",
    "Ayurveda Leadership Coaching",
    "Ayurveda Performance Coaching",
    "Ayurveda Skills Coaching",
    "Ayurveda Personal Development",
    "Ayurveda Self-Improvement",
    "Ayurveda Self-Growth",
    "Ayurveda Self-Help",
    "Ayurveda Self-Care",
    "Ayurveda Mindfulness",
    "Ayurveda Meditation Techniques",
    "Ayurveda Meditation Practices",
    "Ayurveda Guided Meditation",
    "Ayurveda Mindfulness Meditation",
    "Ayurveda Breathwork",
    "Ayurveda Yoga Nidra",
    "Ayurveda Mantras",
    "Ayurveda Chanting",
    "Ayurveda Sound Healing",
    "Ayurveda Sound Therapy",
    "Ayurveda Music Therapy",
    "Ayurveda Art Therapy",
    "Ayurveda Dance Therapy",
    "Ayurveda Movement Therapy",
    "Ayurveda Expressive Arts",
    "Ayurveda Creative Arts",
    "Ayurveda Journaling",
    "Ayurveda Reflection",
    "Ayurveda Contemplation",
    "Ayurveda Diseaseas",
    "Ayurveda Solutions",
    "Yoga",
    "Ayurveda and Yoga",
    "Ayurveda Breathing",
    "Ayurveda Meditation",
    "Ayurvedic Medicine",
    "Ayurvedic Alternatives to Medicine",
    "Ayurvedic Alternatives to Western Medicine",
]


# Create a directory to store downloaded pages
output_dir = "Ayurveda Dataset/ayurveda_texts"
os.makedirs(output_dir, exist_ok=True)

# Load or initialize visited URLs set
visited_file = "visited.pkl"
if os.path.exists(visited_file):
    with open(visited_file, "rb") as f:
        visited_urls = pickle.load(f)
else:
    visited_urls = set()

# Directory containing verified texts
verified_texts_dir = "Processed/books"

# Search depth
num_pages = 3

# Expanded keywords related to Ayurveda
ayurveda_keywords = [
    "Ayurveda",
    "herbal",
    "medicinal",
    "holistic",
    "dosha",
    "panchakarma",
    "vata",
    "pitta",
    "kapha",
    "ayurvedic",
    "western",
    "medicine",
    # "balance",
    # "wellness",
    "alternative medicine",
    # "detoxification",
    # "therapy",
    # "nutrition",
    # "mind-body",
    # "spiritual",
    # "prakriti",
    "shirodhara",
    "abhyanga",
    "rasayana",
    # "natural",
    # "healthy",
    # "meditation",
    # "breathing",
]


def load_verified_texts(directory):
    verified_texts = ""
    for filename in os.listdir(directory):
        filepath = os.path.join(directory, filename)
        with open(filepath, "r", encoding="utf-8") as file:
            verified_texts += file.read() + " "
    return verified_texts


def is_english(content):
    try:
        return detect(content) == "en"
    except:
        return False


def contains_ayurveda_keywords(content, threshold=5):
    keyword_count = sum(
        content.lower().count(keyword.lower()) for keyword in ayurveda_keywords
    )
    return keyword_count > threshold


def compute_similarity(vectorizer, reference_vector, content):
    content_vector = vectorizer.transform([content])
    similarity_matrix = cosine_similarity(reference_vector, content_vector)
    return similarity_matrix[0, 0]


def search_and_download_pages(
    url,
    depth,
    vectorizer,
    reference_vector,
    similarity_threshold=0.6,
    keyword_threshold=3,
):
    if depth == 0:
        return

    try:
        response = requests.get(url)
        soup = BeautifulSoup(response.content, "html.parser")
        page_content = soup.get_text()

        filename = (
            url.replace("http://", "")
            .replace("https://", "")
            .replace("/", "_")
            .replace(".", "_")
            .replace("?", "_")
            .replace("#", "_")
            .replace(" ", "_")
            .strip()
        )
        filename = f"{output_dir}/{filename}.txt"

        if is_english(page_content) and contains_ayurveda_keywords(
            page_content, keyword_threshold
        ):
            similarity_score = compute_similarity(
                vectorizer, reference_vector, page_content
            )
            if similarity_score > similarity_threshold:
                with open(filename, "w", encoding="utf-8") as f:
                    f.write(page_content)
                print(f"Downloaded page {url} with similarity score {similarity_score}")

                result_links = soup.find_all("a", href=True)
                for link in result_links:
                    next_url = link["href"]
                    if next_url.startswith("http") and next_url not in visited_urls:
                        visited_urls.add(next_url)
                        search_and_download_pages(
                            next_url,
                            depth - 1,
                            vectorizer,
                            reference_vector,
                            similarity_threshold,
                            keyword_threshold,
                        )
    except Exception as e:
        print(f"Failed to process {url}: {e}")


if __name__ == "__main__":
    reference_text = load_verified_texts(verified_texts_dir)

    vectorizer = CountVectorizer()
    reference_vector = vectorizer.fit_transform([reference_text])

    for query in search_queries:
        search_and_download_pages(
            f"https://www.bing.com/search?q={query}",
            num_pages,
            vectorizer,
            reference_vector,
        )

    with open(visited_file, "wb") as f:
        pickle.dump(visited_urls, f)
